# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LetsVenture' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LetsVenture
pod 'MZFormSheetPresentationController'
pod 'GoogleMaps', "1.13.2"
pod "AFNetworking", "~> 3.0.0"
pod 'MONActivityIndicatorView'

end
